In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [2]:
df_all = pd.read_csv("48_features.csv", header=0, encoding="utf-8").drop(["Unnamed: 0"], axis=1)
df_all.fillna(0, inplace=True)
df_all = df_all.astype("int32")

In [3]:
df_all.groupby("award_id")["award_id"].count()

award_id
0     4
1    27
2    40
3    86
4     8
5     4
6    11
7     3
8     1
Name: award_id, dtype: int64

In [9]:
labels_grt_10 = [i[0] for i in list(zip([i for i in range(0, 9)], list(df_all.groupby("award_id")['award_id'].count() > 10))) if i[1]]
df_10 = pd.DataFrame(columns=df_all.columns)
for index, row in df_all.iterrows():
    if row["award_id"] in labels_grt_10:
        df_10 = df_10.append(row, ignore_index=True)
df_10.fillna(0, inplace=True)
df_10 = df_10.astype("int32")

In [4]:
df_2 = pd.DataFrame(columns=df_all.columns)
for index, row in df_all.iterrows():
    if row["award_id"] in [2, 3]:
        df_2 = df_2.append(row, ignore_index=True)

df_2.fillna(0, inplace=True)
df_2 = df_2.astype("int32")

In [5]:
def data_to_read(name):
    return eval(name)

In [6]:
# data = data_to_read("df_10")
df = data_to_read("df_2")

df_labels = df["award_id"]
df_user_id = df["user_id"]

df.drop(columns=["award_id", "user_id"], axis=1, inplace=True)

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split, cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns
# from xgboost.sklearn import XGBClassifier
import gc
from sklearn.metrics import accuracy_score, auc, roc_auc_score, roc_curve, mean_squared_error, zero_one_loss

In [10]:
num_round = 1000

data = df.copy()

## category feature one_hot
cate_feature = df.columns
for item in cate_feature:
    data[item] = LabelEncoder().fit_transform(data[item])
    item_dummies = pd.get_dummies(data[item])
    item_dummies.columns = [item + str(i + 1) for i in range(item_dummies.shape[1])]
    data = pd.concat([data, item_dummies], axis=1)
data.drop(cate_feature,axis=1,inplace=True)

### data

In [11]:
data_y = df_labels.factorize()[0]
train_x, test_x, train_y, test_y = train_test_split(data, data_y, test_size=0.1, random_state=100)

### 多项式分布朴素贝叶斯

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
clf = MultinomialNB()
clf = clf.fit(train_x, train_y)
clf.predict(test_x)

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [16]:
test_y

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [18]:
accuracy_score(clf.predict(test_x), test_y)

0.6923076923076923

In [19]:
accuracy_score(clf.predict(data), data_y)

0.753968253968254

### 高斯朴素贝叶斯

In [1]:
from sklearn.naive_bayes import GaussianNB

clf_gauss = GaussianNB()
clf_gauss = clf_gauss.fit(train_x, train_y)
accuracy_score(clf_gauss.predict(data), data_y)

NameError: name 'train_x' is not defined

### 伯努利分布朴素贝叶斯（BernoulliNB）

In [21]:
from sklearn.naive_bayes import BernoulliNB

clf_ber = BernoulliNB()
clf_ber = clf_ber.fit(train_x, train_y)
accuracy_score(clf_ber.predict(data), data_y)

0.7619047619047619

In [22]:
clf_ber.

array([[-0.02531781, -3.68887945, -4.38202663, -0.02531781, -3.68887945,
        -4.38202663, -0.02531781, -3.68887945, -4.38202663, -0.02531781,
        -4.38202663, -3.68887945, -4.38202663, -4.38202663, -0.01257878,
        -4.38202663, -0.01257878, -4.38202663, -4.38202663, -0.01257878,
        -4.38202663, -4.38202663, -0.01257878, -4.38202663, -0.01257878,
        -4.38202663, -0.01257878, -4.38202663, -0.03822121, -3.28341435,
        -0.05129329, -2.99573227, -0.02531781, -3.68887945, -0.02531781,
        -3.68887945, -0.02531781, -3.68887945, -0.02531781, -4.38202663,
        -3.68887945, -0.02531781, -3.68887945, -4.38202663, -0.02531781,
        -4.38202663, -3.68887945, -0.01257878, -0.01257878, -0.01257878,
        -0.01257878, -0.01257878, -0.01257878, -0.06453852, -2.77258872,
        -0.06453852, -4.38202663, -2.77258872, -0.02531781, -3.68887945,
        -0.02531781, -3.68887945, -0.01257878, -4.38202663, -0.01257878,
        -4.38202663, -0.01257878, -4.38202663, -0.0